version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama-service
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 30s
      timeout: 10s
      retries: 3

  hiollama:
    build: .
    container_name: hiollama-app
    environment:
      - DEFAULT_OLLAMA_URL=http://ollama:11434
    ports:
      - "7860:7860"
    depends_on:
      ollama:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  ollama_data: